import { Button, Container } from "reactstrap";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const Home = () => {


  return (
    <Container className="py-5 text-center">
      <h1 className="mt-5 display-1">
        O melhor jeito de comprar o que você ama
      </h1>

      <p className="my-4">
        Lorem, ipsum dolor sit amet consectetur adipisicing elit.
      </p>
      <Link href="/products" className="btn btn-dark px-4 pb-2">
        Conheça nossos produtos
      </Link>
    </Container>
  );

};
export default Home;